config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  get "ranking", to: "toppages#ranking"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to:  "users#new"
  delete "withdraw", to: "users#destroy"
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :post
      get :reply
    end
  end
  
  resources :questions do
    resources :answers, only: [:create]
    get :search, on: :collection
  end
  
  get :tags, to: "tags#tag"
  resources :tags, only: [] do
    collection do
      get :other
      get :work
      get :home
      get :sports
      get :news
      get :study
      get :programming
      get :human
      get :beauty
      get :play
      get :love
      get :school
    end
  end
  
  get :search, to: "questions#search"
  get :result, to: "questions#result"

  resources :answers, only: [:destroy]
  
  resources :favorites, only: [:create, :destroy]
  
  resources :microposts 
  
  get :news, to: "microposts#new"
  
  get :contact, to: "contacts#index" 
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  has_many :questions
  has_many :questions, dependent: :destroy 
  
  has_many :answers
  has_many :answers, dependent: :destroy
  
  has_many :microposts
  
  mount_uploader :picture, PictureUploader

  has_many :favorites
  has_many :favorites, dependent: :destroy 
  has_many :favoritings, through: :favorites, source: :question
  
  def favorite(question)
    unless self == question
      self.favorites.find_or_create_by(question_id: question.id)
    end
  end

  def unfavorite(question)
    favorite = self.favorites.find_by(question_id: question.id)
    favorite.destroy if favorite
  end

  def favoritings?(question)
    self.favoritings.include?(question)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update, :destroy]
  before_action :user_unlogged_in, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy] 

  def show
    @user = User.find(params[:id])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "アカウントを作成できました"
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = "アカウントを作成できませんでした"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    
    counts(@user)
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = "プロフィールを変更しました"
      redirect_to @user
    else
      flash[:danger] = "プロフィールを変更できませんでした"
      render :edit
    end
  end

  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = User.find_by(id: session[:user_id])
    end
    
    @user.destroy
    flash[:success] = "アカウントを削除しました"
    redirect_to root_url
  end
  
  def post
    @user = User.find(params[:id])
    
    @posts = @user.questions.paginate(page: params[:page], per_page: 5).order('created_at desc')
    
     counts(@user)
  end
  
  def reply
    @user = User.find(params[:id])
    
    @replys = @user.answers.paginate(page: params[:page], per_page: 5).order('created_at desc')
  
    counts(@user)
  end
  
  def admin
    @admin = Admin.new
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)  
  end
  
  def correct_user
    if request.referer == nil
      redirect_to root_url
    end
  end
end

app/views/users/edit.html.erb
<%= render "layouts/navbar_profail" %>

<div class="container">
  <div class="text-center">
    <h1>プロフィール変更</h1>
  </div>

  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "layouts/error_messages", model: f.object %>
      
        <div class="form-group">
          <%= f.label :name, "アカウント名" %>
          <%= f.text_field :name, class: "form-control" %>          
        </div>
        
        <div class="form-group">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :picture, "アイコン画像" %>
          <%= f.file_field :picture, class: "d-none", id: "lefile" %>
          
          <div class="input-group">
            <input type="text" id="photoCover" class="form-control" placeholder="画像を選択してください">
            <span class="input-group-btn"><button type="button" class="btn btn-dark" onclick="$('input[id=lefile]').click();">画像を選ぶ</button></span>          
          </div>
        </div>

        <script>
          $('input[id=lefile]').change(function() {
            $('#photoCover').val($(this).val());
          });
        </script>

        <%= f.submit "変更", class: "btn btn-block btn-dark", data: { confirm: "本当に変更しますか？" }%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render "layouts/navbar_start" %>

<div class="container">
  <div class="text-center mt-3">
    <h1 class="font-weight-bold">新規登録</h1>
  </div>
  
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "layouts/error_messages", model: f.object %>
      
        <div class="form-group">
          <%= f.label :name, "アカウント名" %>
          <%= f.text_field :name, class: "form-control" %>          
        </div>
        
        <div class="form-group">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :password, "パスワード" %>
          <%= f.password_field :password, class: "form-control" %>          
        </div>
        
        <div class="form-group">
          <%= f.label :password_confirmation, "確認用パスワード" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>          
        </div>
        
        <%= f.submit "新規登録", class: "btn btn-block btn-dark" %>
      <% end %>
      
      <p class="mt-1">登録済みの方は<%= link_to "こちら", login_path %></p>
    </div>
  </div>
</div>

app/views/users/post.html.erb
<%= render "layouts/navbar_profail" %>

<div class="container">
  <h1 class="reverse-color">投稿一覧</h1>
    <% @posts.each do |post| %>
    <div class="frame">
      <ul class="list-unstyled word-table">
        <li class="toppage-question-title"><h5><%= link_to post.title, question_path(post), class: "link-color" %></h5></li>
      </ul>
    </div>
  <% end %>
  
  <% if @count_questions == 0 %>
    <div class=" m-3">
      <h4>投稿はありません</h4>
    </div>
  <% end %>

  <%= paginate @posts, window: 2 %>
</div>

app/views/users/reply.html.erb
<%= render "layouts/navbar_profail" %>

<div class="container">
  <h1 class="reverse-color">回答一覧</h1>
  <% @replys.each do |reply| %>
    
    <div class="frame reply-frame">
      <div class="word-table">
        <% @question_id = reply.question.id %>
        <div class="reply-content reply-border"><h5>投稿：  <%= link_to reply.question.title, question_path(@question_id), class: "link-color" %></h5></div>
        <div class="reply-content"><h5>回答：  <%= link_to reply.content, question_path(@question_id), class: "link-color" %></h5></div>
      </div>
    </div>
  <% end %>
  
  <% if @count_answers == 0 %>
    <div class=" m-3">
      <h4>回答はありません</h4>
    </div>
  <% end %>

  <%= paginate @replys, window: 2 %>
</div>

app/views/users/show.html.erb
<%= render "layouts/navbar_profail" %>

<div class="container">
  <div class="row">
    <div class="col-sm-3 col-md-5 col-xl-3 mb-4">
      <div class="text-center card">
        <div class="card-header text-center">
          <% if @user.picture? %>
            <%= image_tag @user.picture.url, class: "resize-img" %>
          <% else %>
            <%= image_tag "default_user.png", class: "resize-img" %>
          <% end %>
        </div>
        
        <div class="card-body">
          <% if logged_in? %>
            <% if current_user.admin? && current_user == @user %>
              <div class="mb-2">
                <%= link_to "管理ページ", microposts_path, class: "btn btn-block btn-success" %>
              </div>
            <% end %>
          <% end %>
              
          <div class="mb-2">
            <%= link_to "TOPに戻る", root_path, class: "btn btn-block btn-success" %>
          </div>
            
          <% if logged_in? %>
            <% if current_user == @user || current_user.admin? %>
              <%= link_to "編集", edit_user_path(@user), class: "btn btn-block btn-success" %>
              <div class="mt-2">
                <%= link_to "アカウント削除", @user, method: :delete, data: { confirm: "アカウントを本当にアカウントを削除しますか？" }, class: "btn btn-block btn-danger" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>  
    </div>
    <div class="col-sm-8 col-md-6 col-xl-8 offset-sm-1">
      <table class="table">
        <thead>
          <tr>
            <h3>プロフィール</h3>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">アカウント名</th>
            <td><%= @user.name %></td>
          </tr>
          <% if logged_in? %>
            <% if current_user == @user || current_user.admin? %>
              <tr>
                <th scope="row">メールアドレス</th>
                <td><%= @user.email %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>