config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  get "ranking", to: "toppages#ranking"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to:  "users#new"
  delete "withdraw", to: "users#destroy"
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :post
      get :reply
    end
  end
  
  resources :questions do
    resources :answers, only: [:create]
    get :search, on: :collection
  end
  
  get :tags, to: "tags#tag"
  resources :tags, only: [] do
    collection do
      get :other
      get :work
      get :home
      get :sports
      get :news
      get :study
      get :programming
      get :human
      get :beauty
      get :play
      get :love
      get :school
    end
  end
  
  get :search, to: "questions#search"
  get :result, to: "questions#result"

  resources :answers, only: [:destroy]
  
  resources :favorites, only: [:create, :destroy]
  
  resources :microposts 
  
  get :news, to: "microposts#new"
  
  get :contact, to: "contacts#index" 
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  impressionist
  
  def index
    if logged_in? 
      @question = current_user.questions.build
    end
    @questions = Question.page(params[:page]).per(5).order('created_at desc')
    
    @questions.each do |question|
      impressionist(question)
    end
    
    @microposts = Micropost.limit(3).order('created_at desc')
    @microposts_count = Micropost.all
    micropost_counts(@microposts_count)
  end
  
  def ranking
    @rankings = Question.find(Favorite.group(:question_id).order('count(question_id) desc').limit(10).pluck(:question_id))
  end
end

app/views/toppages/index.html.erb
<%= render "layouts/navbar_home" %>

<div class="container">
  <% if logged_in? %>
    <%= render "questions/upload" %>
  <% else %>
    <%= render "questions/unupload" %>
  <% end %>

  <div class="w-100"> 
    <div class="col-xl-8 p-0 mb-5 float-l">
      <h1 class="reverse-color top-messages-title">メッセージ一覧</h1>
      
      <% @questions.each do |question| %>
        <div class="frame">
          
          <div class="toppage-question-title word-table w-100">
            <h5><%= link_to question.title, question_path(question), class: "link-color" %></h5>
          </div>
          
          <div class="toppage-question-content word-table w-100">
            <div class="word-table w-100 mb-1">
              <%= truncate(question.content, length: 100, omission: ' ') do %>
                <%= link_to "続きを読む…", question_path(question), class: "link-color" %>
              <% end %>
            </div>
            
            <div class="d-flex flex-row align-items-center justify-content-end">
              <div class="mr-3">
                閲覧数：<%= question.impressionist_count %>
              </div>
              
              <% if logged_in? %>
                <%= render "layouts/favorite", question: question %>
              <% else %>
                <%= link_to login_path do %>
                  <i class="far fa-heart"></i>
                <% end %>
              <% end %>
              
              <div class="m-1">
                <div>いいね  <%= question.favoriters.count %></div>
              </div>
            </div>
            
          </div>
        </div>
      <% end %>
      
      <%= paginate @questions, window: 2 %>
    </div>

    <aside class="col-xl-3 offset-xl-1 frame p-0 mb-5 position-r float-r">
      <h1 class="reverse-color text-center">お知らせ</h1>
      <% @microposts.each do |micropost| %>
        <div class="top-micropost-block">
          <div class="top-micropost-title word-table">
            <%= link_to micropost.title, micropost_path(micropost), class: "link-color" %>
          </div> 
          <div class="top-micropost-content word-table">
            <%= truncate(micropost.content, length: 100, omission: ' ') do %>
              <%= link_to "続きを読む…", micropost_path(micropost) %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="micropost-bottom">
        <%= link_to news_path, class: "micropost-bottom" do %>
          <p style="font-size: 20px">一覧へ <span style="font-size: 16px">(<%= @count_micropost %>件)</span></p>
        <% end %>
      </div>
    </aside>
    
    <div class="clear"></div>    
  </div>
</div>

app/views/toppages/ranking.html.erb
<%= render "layouts/navbar_home" %>

<div class="container">
  <div class="row"> 
    <div class="w-100 mb-5">
      <h1 class="rank-title">いいねランキング</h1>
      
      <% @rankings.each.with_index(1) do |rank, i| %>
        <div class="rank-border">
          <h3 class="rank-nonber word-table"><%= i %>位  <%= link_to rank.title, question_path(rank), class: "rank-title-txt link-color" %></h3>
          <ul class="list-unstyled word-table m-0">
            <li class="toppage-question-content rank-font">
              <%= truncate(rank.content, length: 200, omission: ' ') do %>
                <%= link_to "続きを読む…", question_path(rank) %>
              <% end %>
            </li>
            <li class="row d-flex rank-p flex-row">
              <div class="row d-flex w-100 align-items-center justify-content-end">
                <% if logged_in? %>
                  <%= render "layouts/favorite", question: rank %>
                <% else %>
                  <%= link_to login_path do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
              
                <div class="m-1">
                  <div>いいね  <%= rank.favoriters.count %></div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>