config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  get "ranking", to: "toppages#ranking"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to:  "users#new"
  delete "withdraw", to: "users#destroy"
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get :post
      get :reply
    end
  end
  
  resources :questions do
    resources :answers, only: [:create]
    get :search, on: :collection
  end
  
  get :tags, to: "tags#tag"
  resources :tags, only: [] do
    collection do
      get :other
      get :work
      get :home
      get :sports
      get :news
      get :study
      get :programming
      get :human
      get :beauty
      get :play
      get :love
      get :school
    end
  end
  
  get :search, to: "questions#search"
  get :result, to: "questions#result"

  resources :answers, only: [:destroy]
  
  resources :favorites, only: [:create, :destroy]
  
  resources :microposts 
  
  get :news, to: "microposts#new"
  
  get :contact, to: "contacts#index" 
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_favorite.html.erb
<% if current_user.favoritings?(question) %>
  <%= form_with(model: current_user.favorites.find_by(question_id: question.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :question_id, question.id %>
    <%= button_tag type: 'submit', class: 'btn btn-default' do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :question_id, question.id %>
    <%= button_tag type: 'submit', class: 'btn btn-default' do %>
      <i class="far fa-heart"></i>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> mb-0"><%= message %></div>
<% end %>

app/views/layouts/_navbar_home.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand navbar-light bg-light">
    <%= link_to "Failures", root_path, class: "navbar-brand ml-sm-4 logo" %>
    
    <div class="display-sm-none w-100" id="navbarSupportedContent">
      <ul class="navbar-nav justify-content-end">
        <%= link_to "詳細条件", search_path, class: "nav-link" %>
        
        <%= form_with(url: search_questions_path, method: :get, local: true, class: "pr-3") do |f| %>
          <div class="form-group m-0 d-flex flex-row">
            <%= f.text_field :title, class: "form-control", placeholder: "キーワードで検索" %>
            <%= f.submit "検索", class: "btn btn-md btn-dark ml-1" %>
          </div>
        <% end %>
      
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to "プロフィール", user_path(current_user), class: "link-color" %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "link-color" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
      
    <div class="display-sm-block justify-content-end w-100" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-center">
        <div>
          <%= link_to search_path do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
      
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to "プロフィール", user_path(current_user), class: "link-color" %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "link-color" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link nav-sign ml-1" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link nav-sign" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav home-nav">
        <li class="nav-item ml-sm-3"><%= link_to "TOP", root_path, class: "nav-link" %></li>
        <li class="nav-item ml-sm-4"><%= link_to "ランキング", ranking_path, class: "nav-link" %></li>
        <li class="nav-item ml-sm-4"><%= link_to "タグ",  tags_path, class: "nav-link" %></li>
        <li class="nav-item ml-sm-4"><%= link_to "お知らせ", news_path, class: "nav-link" %></li>
        <li class="nav-item ml-sm-4"><%= link_to "お問い合わせ", contact_path, class: "nav-link" %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_navbar_profail.html.erb
<header class="mb-4">
  <nav class="navbar navbar-dark bg-dark">
    <%= link_to "Failures", root_path, class: "navbar-brand ml-sm-4 logo" %>
  </nav>
  <nav class="navbar navbar-expand navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
   <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "プロフィール", user_path(@user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a href="<%= post_user_path(@user) %>" class="nav-link">投稿一覧 <span class="badge badge-secondary"><%= @count_questions %></span></a>
      </li>
      <li class="nav-item">
        <a href="<%= reply_user_path(@user) %>" class="nav-link">回答一覧 <span class="badge badge-secondary"><%= @count_answers %></span></a>
      </li>
    </ul>
  </div>
</nav>
</header>

app/views/layouts/_navbar_start.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <%= link_to "Failures", root_path, class: "navbar-brand ml-sm-4 logo" %>
    
    <div class="w-100" id="navbarNavDropdown">
      <ul class="navbar-nav justify-content-end">
        <% unless logged_in? %>
          <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Failures</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>